version: "3.8"
services:
  backend:
    build: .
    container_name: flask-backend
    ports:
      - "5001:5000"
  frontend:
    image: nginx:alpine
    container_name: nginx-frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend